package controller.utils;

import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;

import java.io.InputStream;
import java.util.Map;
import java.util.Properties;

public class CloudinaryUtil {
    private static Cloudinary cloudinary;

    static {
        try (InputStream input = CloudinaryUtil.class.getClassLoader().getResourceAsStream("cloudinary.properties")) {
            Properties prop = new Properties();
            if (input == null) {
                System.err.println("====== [LỖI KHÔNG TÌM THẤY FILE CLOUDINARY.PROPERTIES] ======");
            } else {
                prop.load(input);
                String cloudName = prop.getProperty("cloudinary.cloud_name");
                String apiKey = prop.getProperty("cloudinary.api_key");
                String apiSecret = prop.getProperty("cloudinary.api_secret");

                if (cloudName != null && apiKey != null && apiSecret != null) {
                    cloudinary = new Cloudinary(ObjectUtils.asMap(
                            "cloud_name", cloudName.trim(),
                            "api_key", apiKey.trim(),
                            "api_secret", apiSecret.trim(),
                            "secure", true
                    ));
                } else {
                    System.err.println("====== [LỖI CẤU HÌNH CLOUDINARY THIẾU THÔNG TIN] ======");
                }
            }
        } catch (Exception e) {
            System.err.println("====== [LỖI KHỞI TẠO CLOUDINARY UTIL] ======");
            e.printStackTrace();
        }
    }

    /**
     * Uploads an image using an InputStream to a specified folder with a random public ID generated by Cloudinary.
     *
     * @param inputStream the image content stream
     * @param folder      the folder name on Cloudinary
     * @return the secure URL of the uploaded image
     * @throws Exception if upload fails
     */
    public static String uploadFile(InputStream inputStream, String folder) throws Exception {
        if (cloudinary == null) {
            throw new IllegalStateException("Cloudinary is not initialized. Please verify src/main/resources/cloudinary.properties.");
        }
        byte[] fileBytes;
        try {
            fileBytes = inputStream.readAllBytes();
        } finally {
            inputStream.close();
        }
        Map params = ObjectUtils.asMap(
                "folder", folder,
                "resource_type", "image"
        );
        Map uploadResult = cloudinary.uploader().upload(fileBytes, params);
        return (String) uploadResult.get("secure_url");
    }

    /**
     * Uploads an image using an InputStream to a specified folder with a custom public ID, overwriting existing files.
     *
     * @param inputStream the image content stream
     * @param folder      the folder name on Cloudinary
     * @param publicId    the custom public ID (filename without extension)
     * @return the secure URL of the uploaded image
     * @throws Exception if upload fails
     */
    public static String uploadFile(InputStream inputStream, String folder, String publicId) throws Exception {
        if (cloudinary == null) {
            throw new IllegalStateException("Cloudinary is not initialized. Please verify src/main/resources/cloudinary.properties.");
        }
        byte[] fileBytes;
        try {
            fileBytes = inputStream.readAllBytes();
        } finally {
            inputStream.close();
        }
        Map params = ObjectUtils.asMap(
                "folder", folder,
                "public_id", publicId,
                "overwrite", true,
                "invalidate", true,
                "resource_type", "image"
        );
        Map uploadResult = cloudinary.uploader().upload(fileBytes, params);
        return (String) uploadResult.get("secure_url");
    }

    /**
     * Deletes an image from Cloudinary using its public ID.
     *
     * @param publicId the public ID of the image to destroy
     * @throws Exception if deletion fails
     */
    public static void deleteFile(String publicId) throws Exception {
        if (cloudinary == null) {
            throw new IllegalStateException("Cloudinary is not initialized. Please verify src/main/resources/cloudinary.properties.");
        }
        cloudinary.uploader().destroy(publicId, ObjectUtils.emptyMap());
    }
}
